domain: grafana-k8s.checkcode.wintech-thai.com
domain1: alm.checkcode.wintech-thai.com
domain2: prom.checkcode.wintech-thai.com

environment: production

kube-prometheus-stack:
  grafana:
    grafana.ini:
      server:
        root_url: grafana-k8s.checkcode.wintech-thai.com
    grafana.ini:
      server:
        root_url: https://grafana-k8s.checkcode.wintech-thai.com
        domain: grafana-k8s.checkcode.wintech-thai.com
