domain: grafana-loki.checkcode.wintech-thai.com

loki-stack:
  grafana:
    grafana.ini:
      server:
        root_url: grafana-loki.checkcode.wintech-thai.com
    grafana.ini:
      server:
        root_url: https://grafana-loki.checkcode.wintech-thai.com
        domain: grafana-loki.checkcode.wintech-thai.com
